### ISSUE TITLE
Installing from readme instructions does not work, Flow is aborted due to ['clip_t'] can not be started.

### ISSUE THREAD

**Issue by flamz3d** [jina-ai/clip-as-service#865]
create clean python 3.7 env on debian linux

run 
pip install clip-server
run
python -m clip_server

result
```python
           raise FileNotFoundError(f'can not find {path}')                                                                       
       FileNotFoundError: can not find clip_server.executors.clip_torch                                                          
ERROR  Flow@4608 Flow is aborted due to ['clip_t'] can not be started.                                        [11/22/22 13:51:07]
Traceback (most recent call last):
  File "/opt/conda/envs/jina/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/envs/jina/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/jina/lib/python3.7/site-packages/clip_server/__main__.py", line 25, in <module>
    with f:
  File "/opt/conda/envs/jina/lib/python3.7/site-packages/jina/orchestrate/flow/base.py", line 1556, in __enter__
    return self.start()
  File "/opt/conda/envs/jina/lib/python3.7/site-packages/jina/orchestrate/flow/builder.py", line 33, in arg_wrapper
    return func(self, *args, **kwargs)
  File "/opt/conda/envs/jina/lib/python3.7/site-packages/jina/orchestrate/flow/base.py", line 1620, in start
    self._wait_until_all_ready()
  File "/opt/conda/envs/jina/lib/python3.7/site-packages/jina/orchestrate/flow/base.py", line 1719, in _wait_until_all_ready
    raise RuntimeFailToStart
jina.excepts.RuntimeFailToStart
```

**Comment by jemmyshin** [comment]
Can you successfully import this?  @flamz3d 
`import importlib` and then `importlib.import_module('clip_server.executors.clip_torch')`
Here is my output for this:
<img width="926" alt="Screen Shot 2022-11-25 at 11 01 38 AM" src="https://user-images.githubusercontent.com/16580382/203891906-209a75b9-c55b-40b8-bee2-504562b039eb.png">

We found that there is a compatibility issue in python3.7 for `torchvision`. For now, the quick solution is to downgrade the `torchvision` to 0.13.0 (the default version is 0.14.0 if you install clip-server using pip install) and everything should be fine.

**Comment by RowenaHe** [comment]
I ran into the same ERROR on both my local machine and Colab. Have you solve it and how?
