### ISSUE TITLE
can we modify disk storage partation for clip embeddings?

### ISSUE THREAD

**Issue by achao2013** [jina-ai/clip-as-service#889]
can we specify a disk storage partation like /mnt/xxx which can use to save the embeddings extracted by the excutors?

**Comment by achao2013** [comment]
@hanxiao @numb3r3

**Comment by numb3r3** [comment]
To persistent the embeddings, you can append a new executor for this purpose. As an example, you can refer to https://clip-as-service.jina.ai/user-guides/retriever/ If you have any questions, feel free to reach out to us.

**Comment by achao2013** [comment]
use annlite-0.5.5,
yaml:
  - name: indexer
    uses:
      jtype: AnnLiteIndexer
      with:
        n_dim: 512
        limit: 5
      metas:
        py_modules:
          - annlite.executor
    workspace: '/mnt/achao/workspace/clipservice_workspace_jidu'

error occurs:

ERROR  indexer/rep-0@3999693 KeyError('n_components') during <class 'jina.serve.runtimes.worker.WorkerRuntime'> initialization                                                         [02/08/23 17:19:34]
        add "--quiet-error" to suppress the exception details
       Traceback (most recent call last):
         File "/mnt/achao/env/miniconda3/envs/jina/lib/python3.8/site-packages/jina/orchestrate/pods/__init__.py", line 79, in run
           runtime = runtime_cls(
         File "/mnt/achao/env/miniconda3/envs/jina/lib/python3.8/site-packages/jina/serve/runtimes/worker/__init__.py", line 39, in __init__
           super().__init__(args, **kwargs)
         File "/mnt/achao/env/miniconda3/envs/jina/lib/python3.8/site-packages/jina/serve/runtimes/asyncio.py", line 77, in __init__
           self._loop.run_until_complete(self.async_setup())
         File "/mnt/achao/env/miniconda3/envs/jina/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
           return future.result()
         File "/mnt/achao/env/miniconda3/envs/jina/lib/python3.8/site-packages/jina/serve/runtimes/worker/__init__.py", line 104, in async_setup
           self._request_handler = WorkerRequestHandler(
         File "/mnt/achao/env/miniconda3/envs/jina/lib/python3.8/site-packages/jina/serve/runtimes/worker/request_handling.py", line 54, in __init__
           self._load_executor(
         File "/mnt/achao/env/miniconda3/envs/jina/lib/python3.8/site-packages/jina/serve/runtimes/worker/request_handling.py", line 204, in _load_executor
           self._executor: BaseExecutor = BaseExecutor.load_config(
         File "/mnt/achao/env/miniconda3/envs/jina/lib/python3.8/site-packages/jina/jaml/__init__.py", line 766, in load_config
           obj = JAML.load(tag_yml, substitute=False, runtime_args=runtime_args)
         File "/mnt/achao/env/miniconda3/envs/jina/lib/python3.8/site-packages/jina/jaml/__init__.py", line 174, in load
           r = yaml.load(stream, Loader=get_jina_loader_with_runtime(runtime_args))
         File "/mnt/achao/env/miniconda3/envs/jina/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
           return loader.get_single_data()
         File "/mnt/achao/env/miniconda3/envs/jina/lib/python3.8/site-packages/yaml/constructor.py", line 51, in get_single_data
           return self.construct_document(node)
         File "/mnt/achao/env/miniconda3/envs/jina/lib/python3.8/site-packages/yaml/constructor.py", line 55, in construct_document
           data = self.construct_object(node)
         File "/mnt/achao/env/miniconda3/envs/jina/lib/python3.8/site-packages/yaml/constructor.py", line 100, in construct_object
           data = constructor(self, node)
         File "/mnt/achao/env/miniconda3/envs/jina/lib/python3.8/site-packages/jina/jaml/__init__.py", line 582, in _from_yaml
           return get_parser(cls, version=data.get('version', None)).parse(
         File "/mnt/achao/env/miniconda3/envs/jina/lib/python3.8/site-packages/jina/jaml/parsers/executor/legacy.py", line 46, in parse
           obj = cls(
         File "/mnt/achao/env/miniconda3/envs/jina/lib/python3.8/site-packages/jina/serve/executors/decorators.py", line 60, in arg_wrapper
           f = func(self, *args, **kwargs)
         File "/mnt/achao/env/miniconda3/envs/jina/lib/python3.8/site-packages/jina/serve/helper.py", line 73, in arg_wrapper
           f = func(self, *args, **kwargs)
         File "/mnt/achao/env/miniconda3/envs/jina/lib/python3.8/site-packages/annlite/executor.py", line 107, in __init__
           self._index = DocumentArray(storage='annlite', config=config)
         File "/mnt/achao/env/miniconda3/envs/jina/lib/python3.8/site-packages/docarray/array/base.py", line 12, in __init__
           self._init_storage(*args, **kwargs)
         File "/mnt/achao/env/miniconda3/envs/jina/lib/python3.8/site-packages/docarray/array/storage/annlite/backend.py", line 88, in _init_storage
           config = dataclass_from_dict(AnnliteConfig, config)
         File "/mnt/achao/env/miniconda3/envs/jina/lib/python3.8/site-packages/docarray/helper.py", line 367, in dataclass_from_dict
           return klass(**{f: dataclass_from_dict(fieldtypes[f], dikt[f]) for f in dikt})
         File "/mnt/achao/env/miniconda3/envs/jina/lib/python3.8/site-packages/docarray/helper.py", line 367, in <dictcomp>
           return klass(**{f: dataclass_from_dict(fieldtypes[f], dikt[f]) for f in dikt})
       KeyError: 'n_components'
ERROR  Flow@3999508 Flow is aborted due to ['indexer'] can not be started.

@numb3r3
